/** V83 interaction checks against the real local app, using only fictional account data. */
import { session, capture, uid } from './session.mjs';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const out=process.env.ANCIENT_PULLS_QA_REPORTS||path.join(root,'docs/verification');
fs.mkdirSync(path.join(out,'screenshots'),{recursive:true});
let app;const checks=[],profiles=[];
async function check(name,fn){console.log('CHECK '+name);await fn();checks.push(name);console.log('PASS '+name);}
const menu=async p=>{await p.getByTestId('astra-staff').click();await p.locator('#astra-requests').waitFor();};
const close=async p=>{await p.keyboard.press('Escape');await p.waitForTimeout(120);};
const screenshot=async(p,name)=>{await p.waitForTimeout(400);return capture(p,path.join(out,'screenshots/v83-'+name+'.png'));};
async function profile(p,label){await p.waitForFunction(()=>{const value=document.querySelector('.as-puppet canvas')?.dataset.performance;return value&&JSON.parse(value).samples===600;},{},{timeout:25000});const result=JSON.parse(await p.locator('.as-puppet canvas').getAttribute('data-performance'));profiles.push({label,...result});assert.ok(result.paintP95Ms<16.67,`${label}: p95 draw work must fit a 60 Hz frame`);console.log('FRAME PROFILE '+JSON.stringify(profiles.at(-1)));}
try{
 app=await session({profile:true});let {page:p,state:s}=app;
 await check('A calls Astra; idle animation stays anchored and fits the drawing budget',async()=>{await p.keyboard.press('a');await p.getByTestId('astra-staff').waitFor();await p.waitForTimeout(900);await profile(p,'1440×960, software-rendered Chromium, desktop idle');await screenshot(p,'desktop-astra');});
 await check('Request search finds synonyms and has a clearable empty state',async()=>{await menu(p);const input=p.getByRole('searchbox',{name:'Find an Astra request'});await input.fill('sound');assert.equal(await p.locator('.as-request-list>button').count(),1);assert.ok(await p.getByRole('button',{name:'I want to change the settings',exact:false}).isVisible());await input.fill('zzyyxx');assert.ok(await p.getByText('No requests found.',{exact:false}).isVisible());await p.getByRole('button',{name:'Clear request search'}).click();assert.equal(await p.locator('.as-request-list>button').count(),11);await screenshot(p,'desktop-requests');});
 await check('Sound can be enabled, previewed and muted inside preferences',async()=>{await p.getByRole('button',{name:'I want to change the settings',exact:false}).click();await p.getByRole('heading',{name:'Player preferences'}).waitFor();const sound=p.getByRole('checkbox',{name:'Astra sounds',exact:false}),preview=p.getByRole('button',{name:'Preview wish sound'});assert.ok(await preview.isDisabled());await p.getByText('Astra sounds',{exact:true}).click();assert.ok(await sound.isChecked());assert.ok(await preview.isEnabled());await preview.click();await sound.focus();await p.keyboard.press('Space');assert.equal(await sound.isChecked(),false);assert.ok(await preview.isDisabled());});
 await check('Sky shortcuts cannot open a hidden dialog beneath settings',async()=>{await p.getByRole('heading',{name:'Player preferences'}).click();await p.keyboard.press('/');assert.equal(await p.getByRole('dialog',{name:'Find a card',exact:true}).count(),0);await close(p);assert.equal(await p.getByRole('dialog').count(),0);});
 await check('Balance opens the nine-step colour guide without a recharge offer',async()=>{await p.getByRole('button',{name:'34 wishes. About staff colours'}).click();assert.equal(await p.locator('.as-power-legend li').count(),9);assert.ok(await p.getByText('Colours stop changing at 250 wishes.',{exact:false}).isVisible());assert.equal(await p.getByRole('button',{name:'Recharge wishes',exact:true}).count(),0);await screenshot(p,'staff-colours');await close(p);});
 await check('How to play explains the arc, keyboard and cancelling',async()=>{await p.getByRole('button',{name:'How to play',exact:true}).click();assert.ok(await p.getByText('Change your mind?',{exact:false}).isVisible());assert.ok(await p.getByText('→ then Enter',{exact:true}).isVisible());await close(p);});
 await check('Card search starts with 40 results, loads more and clears reliably',async()=>{await p.keyboard.press('/');const panel=p.getByRole('dialog',{name:'Find a card',exact:true});await panel.waitFor();assert.equal(await panel.locator('button[class*="cardRow"]').count(),40);await panel.getByRole('button',{name:'Show more results'}).click();assert.equal(await panel.locator('button[class*="cardRow"]').count(),72);const input=panel.getByRole('textbox');await input.fill('Moonlit');assert.equal(await panel.locator('button[class*="cardRow"]').count(),8);await panel.getByRole('button',{name:'Clear search'}).click();assert.equal(await panel.locator('button[class*="cardRow"]').count(),40);assert.equal(await input.evaluate(el=>el===document.activeElement),true);await close(p);});
 await check('Astra opens the galaxy finder; rank search remains usable',async()=>{await menu(p);await p.getByRole('button',{name:'Find someone’s galaxy',exact:false}).click();const panel=p.getByRole('dialog',{name:'Find a galaxy',exact:true});await panel.waitFor();await panel.getByRole('textbox').fill('#7');assert.equal(await panel.locator('button[class*="galaxyRow"]').count(),1);assert.ok(await panel.getByText('Lukas Moon',{exact:true}).isVisible());assert.equal(await p.locator('.as-guide').getAttribute('inert'),'');await close(p);});
 await check('Route panels restore their scroll and keyboard focus over the same sky',async()=>{await p.evaluate(()=>window.__v83Sky=document.querySelector('[data-observatory-level] canvas'));await menu(p);await p.getByRole('button',{name:'Open my binder',exact:false}).click();await p.locator('.as-panel-content').waitFor();await p.waitForFunction(()=>{const el=document.querySelector('.as-panel-content');return el&&el.scrollHeight-el.clientHeight>100;});const desired=await p.locator('.as-panel-content').evaluate(el=>{el.scrollTop=Math.min(400,el.scrollHeight-el.clientHeight);return el.scrollTop;});await p.waitForTimeout(100);await p.getByRole('button',{name:'Close panel and return to constellation'}).click();await p.waitForURL('**/observatory');await p.waitForTimeout(150);assert.equal(await p.getByTestId('astra-staff').evaluate(el=>el===document.activeElement),true);await menu(p);await p.getByRole('button',{name:'Open my binder',exact:false}).click();await p.waitForURL('**/collection');await p.waitForFunction(value=>Math.abs((document.querySelector('.as-panel-content')?.scrollTop||0)-value)<2,desired);assert.equal(await p.evaluate(()=>window.__v83Sky===document.querySelector('[data-observatory-level] canvas')),true);await close(p);});
 await check('Offline pull creates no pending key and makes no wish request; reconnect is announced',async()=>{await app.context.setOffline(true);await p.getByTestId('astra-staff').focus();await p.keyboard.press('ArrowRight');await p.keyboard.press('Enter');await p.getByText('You’re offline. Reconnect, then swing my staff again.',{exact:true}).waitFor();assert.equal(s.calls.length,0);assert.equal(await p.evaluate(user=>sessionStorage.getItem('ancientpulls:pending-wish:'+user),uid),null);await app.context.setOffline(false);await p.getByText('Connected again. Your stars are waiting.',{exact:true}).waitFor();assert.equal(await p.getByRole('dialog',{name:'Your wish',exact:true}).count(),0);});
 await check('Straight-down drag cannot wish; a complete 45 degree arc makes one wish',async()=>{const staff=p.getByTestId('astra-staff');await p.waitForTimeout(400);const box=await p.locator('.as-puppet').boundingBox(),b=await staff.boundingBox(),x=b.x+b.width/2,y=b.y+b.height/2;await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x,y+112,{steps:10});await p.mouse.up();assert.equal(s.calls.length,0);await p.waitForTimeout(400);await p.mouse.move(x,y);await p.mouse.down();for(let i=1;i<=20;i++)await p.mouse.move(box.x+168+82*Math.sin(i/20*Math.PI/4),box.y+163-82*Math.cos(i/20*Math.PI/4));await p.waitForTimeout(180);assert.equal(await p.locator('.as-staff').getAttribute('data-armed'),'true');await screenshot(p,'staff-at-45-degrees');await p.mouse.up();await p.getByTestId('wish-result').waitFor();assert.equal(s.calls.length,1);assert.equal(s.balance,33);await p.getByRole('button',{name:'Place in my constellation',exact:false}).click();});
 assert.deepEqual(s.errors,[]);await app.browser.close();app=null;
 app=await session({mobile:true,profile:true});({page:p,state:s}=app);
 await check('Mobile Astra renders within the frame budget and the 45 degree target fits 320px',async()=>{await p.getByRole('button',{name:'Call Astra',exact:true}).tap();await p.waitForTimeout(900);await profile(p,'390×844, software-rendered Chromium, touch-emulated idle');await screenshot(p,'mobile-astra');await p.setViewportSize({width:320,height:740});await p.waitForTimeout(500);await p.getByTestId('astra-staff').focus();await p.keyboard.press('ArrowRight');await p.waitForTimeout(500);const b=await p.getByTestId('astra-staff').boundingBox();assert.ok(b.x>=0&&b.x+b.width<=320);await screenshot(p,'mobile-320-arc');await p.keyboard.press('Escape');});
 await check('Landscape keeps touch targets and guidance reachable',async()=>{await p.setViewportSize({width:844,height:390});await p.waitForTimeout(500);const help=await p.getByRole('button',{name:'How to play',exact:true}).boundingBox();assert.ok(help.y+help.height<=390);await menu(p);const b=await p.locator('#astra-requests').boundingBox();assert.ok(b.y+b.height<=390);const rows=await p.locator('.as-request-list>button').evaluateAll(els=>els.slice(0,3).map(el=>el.getBoundingClientRect().bottom));assert.ok(rows[2]<=b.y+b.height);await screenshot(p,'landscape-menu');await close(p);});
 assert.deepEqual(s.errors,[]);await app.browser.close();app=null;
 app=await session();({page:p,state:s}=app);
 // A separate anonymous context avoids the fixture re-injecting its fake session on navigation.
 const signInUrl=new URL('/sign-in',p.url()).href;await app.context.close();const anonymous=await app.browser.newContext({viewport:{width:1440,height:960}});p=await anonymous.newPage();app.page=p;p.on('pageerror',error=>s.errors.push(error.message));await p.goto(signInUrl,{waitUntil:'networkidle'});
 await check('Password has a stable accessible label and a labelled visibility toggle',async()=>{const password=p.getByLabel('Password',{exact:true});await password.waitFor();assert.equal(await password.getAttribute('type'),'password');const show=p.getByRole('button',{name:'Show password',exact:true});await show.click();assert.equal(await password.getAttribute('type'),'text');assert.equal(await p.getByRole('button',{name:'Hide password',exact:true}).getAttribute('aria-pressed'),'true');await p.getByRole('button',{name:'Hide password',exact:true}).click();assert.equal(await password.getAttribute('type'),'password');await password.dispatchEvent('keydown',{key:'A',modifierCapsLock:true});assert.ok(await p.getByText('Caps Lock is on.',{exact:true}).isVisible());await password.dispatchEvent('keyup',{key:'A',modifierCapsLock:false});assert.equal(await p.getByText('Caps Lock is on.',{exact:true}).count(),0);});
 assert.deepEqual(s.errors,[]);
 fs.writeFileSync(path.join(out,'browser-v83-results.json'),JSON.stringify({passed:checks.length,checks,profiles,environment:'Headless Chromium, software rendering, fictional local account data. Frame cadence is measured, not guaranteed across devices.'},null,2));
 console.log(JSON.stringify({passed:checks.length,profiles}));
}catch(error){if(app){await screenshot(app.page,'failure').catch(()=>{});console.log('PAGE',await app.page.locator('body').innerText());console.log('ERRORS',app.state.errors);}throw error;}finally{if(app)await app.browser.close();}
